title: 병팔's Blog
description: 새롭게 배운내용, 경험한 내용을 꾸준히 남기자
author: byunginK
github: https://github.com/byunginK
about: Web Programmer가 되고 싶다
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
   
    - icon: fa-github
      link: "https://github.com/byunginK"

share:
  twitter_username: ''
  fb_appid: ''

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/


url: "https://byunginK.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
